import Head from 'next/head';
import Link from 'next/link';

import { useState } from 'react';
import HighchartsReact from 'highcharts-react-official';
import Highcharts from "highcharts/highstock";

import { portfolios } from '../data/portfolio';

export default function FeedbackPage() {

  const options = {
    chart: {
      type: 'spline'
    },
    yAxis: {
      title: {
          text: 'Value in USD'
      }
  },
    title: {
      text: 'Portfolio Value Over Time'
    },
    series: [
      {
        name: 'Main Portfolio',
        data: portfolios.map((p) => p.total)
      }
    ]
  };

  return (
    <div>
      <Head>
        <title>Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        
        <div className="container mx-auto max-w-screen-lg px-4">
        
        <div className="flex items-center justify-between flex-wrap">

          <h1 className="text-3xl mb-5 font-bold tracking-wide text-white">
          Portfolios
          </h1>
          <div className="order-3 mt-2 flex-shrink-0 w-full sm:order-2 sm:mt-0 sm:w-auto">
          <Link href='/create'>
          <a className="flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-sky-600 bg-white hover:bg-indigo-50">
          Create</a>
          </Link>
        </div>
        <div>

      </div>
        </div>
          <section className="flex flex-col">
            <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div className="shadow overflow-hidden border-b border-gray-800 rounded-lg">
                  <table className="min-w-full divide-y divide-gray-800 ">
                    <thead className="bg-gray-800">
                      <tr>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Date
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Total
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Allocations
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >

                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-gray-700 divide-y divide-gray-500">
                      {portfolios.map((item, id) => (
                        <tr key={item.id}>
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-white">
                            {item.date}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-white">
                            ${item.total.toLocaleString()}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-white truncate">
                              {item.portfolio.length}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-white truncate">
                            <Link href={`/portfolios/${item.id}`}>
                              View
                            </Link>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                
              </div>
              
            </div>
            <div className='mt-10'>
              <HighchartsReact highcharts={Highcharts} options={options} />
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
